# Site settings
title: Soma Recording Studios
email: somarecordingstudios@gmail.com
url: "http://zackhanni.github.io" # the base hostname & protocol for your site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: somaaamusic
github_username:  zackhanni

# Footer settings
footer: Soma Recording Studios

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/somaaamusic
  - title: thumbtack
    url: https://www.thumbtack.com/profile/services/2PD0eXy78jLD6A
  - title: youtube
    url: https://www.youtube.com/user/basscreators

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - octopress-debugger
